-- MySQL Script generated by MySQL Workbench
-- Wed Nov 20 15:48:22 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`WARD`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`WARD` ;

CREATE TABLE IF NOT EXISTS `mydb`.`WARD` (
  `WardID_pk` INT NOT NULL,
  `Name` VARCHAR(45) NULL,
  PRIMARY KEY (`WardID_pk`),
  UNIQUE INDEX `WARD_ID_UNIQUE` (`WardID_pk` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ROOMS`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`ROOMS` ;

CREATE TABLE IF NOT EXISTS `mydb`.`ROOMS` (
  `Room#_pk` INT NOT NULL,
  `Name` VARCHAR(45) NULL,
  `ROOMS_WardID_fk` INT NOT NULL,
  PRIMARY KEY (`Room#_pk`, `ROOMS_WardID_fk`),
  UNIQUE INDEX `Room#_UNIQUE` (`Room#_pk` ASC) VISIBLE,
  CONSTRAINT `ROOM_WardID_fk`
    FOREIGN KEY (`ROOMS_WardID_fk`)
    REFERENCES `mydb`.`WARD` (`WardID_pk`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`EQUIPMENT`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`EQUIPMENT` ;

CREATE TABLE IF NOT EXISTS `mydb`.`EQUIPMENT` (
  `Equiptment_ID_pk` INT NOT NULL,
  `Name` VARCHAR(45) NULL,
  `Type` VARCHAR(45) NULL,
  `EQUIPMENT_Room#_fk` INT NOT NULL,
  PRIMARY KEY (`Equiptment_ID_pk`, `EQUIPMENT_Room#_fk`),
  UNIQUE INDEX `Equiptment_ID_UNIQUE` (`Equiptment_ID_pk` ASC) VISIBLE,
  INDEX `ROOM_Room#_idx` (`EQUIPMENT_Room#_fk` ASC) VISIBLE,
  CONSTRAINT `EQUIPMENT_Room#_fk`
    FOREIGN KEY (`EQUIPMENT_Room#_fk`)
    REFERENCES `mydb`.`ROOMS` (`Room#_pk`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`BED`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`BED` ;

CREATE TABLE IF NOT EXISTS `mydb`.`BED` (
  `Bed#_pk` INT NOT NULL,
  `BED_WardID_fk` INT NOT NULL,
  PRIMARY KEY (`Bed#_pk`, `BED_WardID_fk`),
  UNIQUE INDEX `Bed#_UNIQUE` (`Bed#_pk` ASC) VISIBLE,
  CONSTRAINT `BED_WardID_fk`
    FOREIGN KEY (`BED_WardID_fk`)
    REFERENCES `mydb`.`WARD` (`WardID_pk`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`MEDICINE`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`MEDICINE` ;

CREATE TABLE IF NOT EXISTS `mydb`.`MEDICINE` (
  `MedicineID_pk` INT NOT NULL,
  `MedicineName` VARCHAR(45) NULL,
  `Form` VARCHAR(45) NULL,
  PRIMARY KEY (`MedicineID_pk`),
  UNIQUE INDEX `MedicineID_UNIQUE` (`MedicineID_pk` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`PATIENTS`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`PATIENTS` ;

CREATE TABLE IF NOT EXISTS `mydb`.`PATIENTS` (
  `PATIENTS_USERID_pk` INT NOT NULL,
  `Password` VARCHAR(45) NULL,
  `FName` VARCHAR(45) NULL,
  `LName` VARCHAR(45) NULL,
  `HealthCare#` INT NOT NULL,
  PRIMARY KEY (`PATIENTS_USERID_pk`),
  UNIQUE INDEX `USERID_UNIQUE` (`PATIENTS_USERID_pk` ASC) VISIBLE,
  UNIQUE INDEX `HealthCare#_UNIQUE` (`HealthCare#` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`STAFF`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`STAFF` ;

CREATE TABLE IF NOT EXISTS `mydb`.`STAFF` (
  `STAFF_UserID_pk` INT NOT NULL,
  `Password` VARCHAR(45) NULL,
  `SSN` INT NOT NULL,
  `FName` VARCHAR(45) NULL,
  `LName` VARCHAR(45) NULL,
  `Salary` INT NULL,
  `JobTitle` VARCHAR(45) NULL,
  PRIMARY KEY (`STAFF_UserID_pk`),
  UNIQUE INDEX `UserID_UNIQUE` (`STAFF_UserID_pk` ASC) VISIBLE,
  UNIQUE INDEX `SSN_UNIQUE` (`SSN` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`NURSE`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`NURSE` ;

CREATE TABLE IF NOT EXISTS `mydb`.`NURSE` (
  `NURSE_UserID_fk` INT NOT NULL,
  `NURSE_WardID_fk` INT NOT NULL,
  PRIMARY KEY (`NURSE_UserID_fk`, `NURSE_WardID_fk`),
  UNIQUE INDEX `UserID_UNIQUE` (`NURSE_UserID_fk` ASC) VISIBLE,
  CONSTRAINT `NURSE_UserID_fk`
    FOREIGN KEY (`NURSE_UserID_fk`)
    REFERENCES `mydb`.`STAFF` (`STAFF_UserID_pk`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `NURSE_WardID_fk`
    FOREIGN KEY (`NURSE_WardID_fk`)
    REFERENCES `mydb`.`WARD` (`WardID_pk`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`DOCTOR`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`DOCTOR` ;

CREATE TABLE IF NOT EXISTS `mydb`.`DOCTOR` (
  `DOCTOR_UserID_fk` INT NOT NULL,
  `IsSpecialist` TINYINT NOT NULL,
  `Specialty` VARCHAR(45) NULL,
  PRIMARY KEY (`DOCTOR_UserID_fk`),
  UNIQUE INDEX `UserID_UNIQUE` (`DOCTOR_UserID_fk` ASC) VISIBLE,
  CONSTRAINT `DOCTOR_UserID_fk`
    FOREIGN KEY (`DOCTOR_UserID_fk`)
    REFERENCES `mydb`.`STAFF` (`STAFF_UserID_pk`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ADMIN`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`ADMIN` ;

CREATE TABLE IF NOT EXISTS `mydb`.`ADMIN` (
  `ADMIN_UserID_fk` INT NOT NULL,
  `ClearanceLevel` INT NOT NULL,
  PRIMARY KEY (`ADMIN_UserID_fk`),
  UNIQUE INDEX `UserID_UNIQUE` (`ADMIN_UserID_fk` ASC) VISIBLE,
  CONSTRAINT `ADMIN_UserID_fk`
    FOREIGN KEY (`ADMIN_UserID_fk`)
    REFERENCES `mydb`.`STAFF` (`STAFF_UserID_pk`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`DOCTOR_DEGREES`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`DOCTOR_DEGREES` ;

CREATE TABLE IF NOT EXISTS `mydb`.`DOCTOR_DEGREES` (
  `DOCDEG_UserID_fk` INT NOT NULL,
  `Degree` VARCHAR(128) NOT NULL,
  PRIMARY KEY (`DOCDEG_UserID_fk`),
  CONSTRAINT `DOCDEG_UserID_fk`
    FOREIGN KEY (`DOCDEG_UserID_fk`)
    REFERENCES `mydb`.`DOCTOR` (`DOCTOR_UserID_fk`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`NURSES_CERTIFICATION`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`NURSES_CERTIFICATION` ;

CREATE TABLE IF NOT EXISTS `mydb`.`NURSES_CERTIFICATION` (
  `NURCER_UserID_fk` INT NOT NULL,
  `Certification` VARCHAR(128) NOT NULL,
  PRIMARY KEY (`NURCER_UserID_fk`),
  CONSTRAINT `NURCER_UserID_fk`
    FOREIGN KEY (`NURCER_UserID_fk`)
    REFERENCES `mydb`.`NURSE` (`NURSE_UserID_fk`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`APPOINTMENT`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`APPOINTMENT` ;

CREATE TABLE IF NOT EXISTS `mydb`.`APPOINTMENT` (
  `PATIENT_UserID` INT NOT NULL,
  `Time` TIME NULL,
  `Date` DATE NULL,
  `Reason` VARCHAR(128) NULL,
  `DAPT_UserID_fk` INT NOT NULL,
  PRIMARY KEY (`PATIENT_UserID`, `DAPT_UserID_fk`),
  CONSTRAINT `PAPT_UserID_fk`
    FOREIGN KEY (`PATIENT_UserID`)
    REFERENCES `mydb`.`PATIENTS` (`PATIENTS_USERID_pk`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `DAPT_UserID_fk`
    FOREIGN KEY (`DAPT_UserID_fk`)
    REFERENCES `mydb`.`DOCTOR` (`DOCTOR_UserID_fk`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`PRESCRIBED`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`PRESCRIBED` ;

CREATE TABLE IF NOT EXISTS `mydb`.`PRESCRIBED` (
  `PPRESC_UserID_fk` INT NOT NULL,
  `DPRESC_UserID_fk` INT NOT NULL,
  `MEDICINE_MedicineID` INT NOT NULL,
  `Dosage` VARCHAR(45) NULL,
  `Frequency` VARCHAR(45) NULL,
  `IsRefillable` TINYINT NULL,
  PRIMARY KEY (`PPRESC_UserID_fk`, `DPRESC_UserID_fk`, `MEDICINE_MedicineID`),
  INDEX `DOCTOR_UserID_idx` (`DPRESC_UserID_fk` ASC) VISIBLE,
  INDEX `MEDICINE_MedicineID_idx` (`MEDICINE_MedicineID` ASC) VISIBLE,
  CONSTRAINT `PPRESC_UserID_fk`
    FOREIGN KEY (`PPRESC_UserID_fk`)
    REFERENCES `mydb`.`PATIENTS` (`PATIENTS_USERID_pk`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `DPRESC_UserID_fk`
    FOREIGN KEY (`DPRESC_UserID_fk`)
    REFERENCES `mydb`.`DOCTOR` (`DOCTOR_UserID_fk`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `MPRESC_MedicineID_fk`
    FOREIGN KEY (`MEDICINE_MedicineID`)
    REFERENCES `mydb`.`MEDICINE` (`MedicineID_pk`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`DOCTOR_IS_IN_WARD`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`DOCTOR_IS_IN_WARD` ;

CREATE TABLE IF NOT EXISTS `mydb`.`DOCTOR_IS_IN_WARD` (
  `DW_UserID_fk` INT NOT NULL,
  `DW_WardID_fk` INT NOT NULL,
  PRIMARY KEY (`DW_UserID_fk`, `DW_WardID_fk`),
  INDEX `WARD_WardID_idx` (`DW_WardID_fk` ASC) VISIBLE,
  CONSTRAINT `DW_UserID_fk`
    FOREIGN KEY (`DW_UserID_fk`)
    REFERENCES `mydb`.`DOCTOR` (`DOCTOR_UserID_fk`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `DW_WardID_fk`
    FOREIGN KEY (`DW_WardID_fk`)
    REFERENCES `mydb`.`WARD` (`WardID_pk`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`PATIENT_IS_IN_WARD`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`PATIENT_IS_IN_WARD` ;

CREATE TABLE IF NOT EXISTS `mydb`.`PATIENT_IS_IN_WARD` (
  `PW_UserID_fk` INT NOT NULL,
  `PW_WardID_fk` INT NOT NULL,
  PRIMARY KEY (`PW_UserID_fk`, `PW_WardID_fk`),
  INDEX `WARD_WardID_idx` (`PW_WardID_fk` ASC) VISIBLE,
  CONSTRAINT `PW_UserID_fk`
    FOREIGN KEY (`PW_UserID_fk`)
    REFERENCES `mydb`.`PATIENTS` (`PATIENTS_USERID_pk`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `PW_WardID_fk`
    FOREIGN KEY (`PW_WardID_fk`)
    REFERENCES `mydb`.`WARD` (`WardID_pk`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`PATIENT_IS_IN_ROOM`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`PATIENT_IS_IN_ROOM` ;

CREATE TABLE IF NOT EXISTS `mydb`.`PATIENT_IS_IN_ROOM` (
  `PR_UserID_fk` INT NOT NULL,
  `PR_Room#_fk` INT NOT NULL,
  PRIMARY KEY (`PR_UserID_fk`, `PR_Room#_fk`),
  INDEX `ROOM_Room#_idx` (`PR_Room#_fk` ASC) VISIBLE,
  CONSTRAINT `PR_UserID_fk`
    FOREIGN KEY (`PR_UserID_fk`)
    REFERENCES `mydb`.`PATIENTS` (`PATIENTS_USERID_pk`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `PR_Room#_fk`
    FOREIGN KEY (`PR_Room#_fk`)
    REFERENCES `mydb`.`ROOMS` (`Room#_pk`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
