-- MySQL Script generated by MySQL Workbench
-- Tue Nov 19 13:33:47 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`WARD`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`WARD` ;

CREATE TABLE IF NOT EXISTS `mydb`.`WARD` (
  `WardID` INT NOT NULL,
  `Name` VARCHAR(45) NULL,
  PRIMARY KEY (`WardID`),
  UNIQUE INDEX `WARD_ID_UNIQUE` (`WardID` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ROOMS`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`ROOMS` ;

CREATE TABLE IF NOT EXISTS `mydb`.`ROOMS` (
  `Room#` INT NOT NULL,
  `Name` VARCHAR(45) NULL,
  `WARD_WardID` INT NOT NULL,
  PRIMARY KEY (`Room#`, `WARD_WardID`),
  UNIQUE INDEX `Room#_UNIQUE` (`Room#` ASC) VISIBLE,
  CONSTRAINT `WARD_WardID`
    FOREIGN KEY (`WARD_WardID`)
    REFERENCES `mydb`.`WARD` (`WardID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`EQUIPMENT`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`EQUIPMENT` ;

CREATE TABLE IF NOT EXISTS `mydb`.`EQUIPMENT` (
  `Equiptment_ID` INT NOT NULL,
  `Name` VARCHAR(45) NULL,
  `Type` VARCHAR(45) NULL,
  `ROOM_Room#` INT NOT NULL,
  PRIMARY KEY (`Equiptment_ID`, `ROOM_Room#`),
  UNIQUE INDEX `Equiptment_ID_UNIQUE` (`Equiptment_ID` ASC) VISIBLE,
  CONSTRAINT `ROOM_Room#`
    FOREIGN KEY (`ROOM_Room#`)
    REFERENCES `mydb`.`ROOMS` (`Room#`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`BED`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`BED` ;

CREATE TABLE IF NOT EXISTS `mydb`.`BED` (
  `Bed#` INT NOT NULL,
  `WARD_WardID` INT NOT NULL,
  PRIMARY KEY (`Bed#`, `WARD_WardID`),
  UNIQUE INDEX `Bed#_UNIQUE` (`Bed#` ASC) VISIBLE,
  CONSTRAINT `WARD_WardID`
    FOREIGN KEY (`WARD_WardID`)
    REFERENCES `mydb`.`WARD` (`WardID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`MEDICINE`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`MEDICINE` ;

CREATE TABLE IF NOT EXISTS `mydb`.`MEDICINE` (
  `MedicineID` INT NOT NULL,
  `MedicineName` VARCHAR(45) NULL,
  `Form` VARCHAR(45) NULL,
  PRIMARY KEY (`MedicineID`),
  UNIQUE INDEX `MedicineID_UNIQUE` (`MedicineID` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`PATIENTS`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`PATIENTS` ;

CREATE TABLE IF NOT EXISTS `mydb`.`PATIENTS` (
  `USERID` INT NOT NULL,
  `Password` VARCHAR(45) NULL,
  `FName` VARCHAR(45) NULL,
  `LName` VARCHAR(45) NULL,
  `HealthCare#` INT NOT NULL,
  PRIMARY KEY (`USERID`),
  UNIQUE INDEX `USERID_UNIQUE` (`USERID` ASC) VISIBLE,
  UNIQUE INDEX `HealthCare#_UNIQUE` (`HealthCare#` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`STAFF`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`STAFF` ;

CREATE TABLE IF NOT EXISTS `mydb`.`STAFF` (
  `UserID` INT NOT NULL,
  `Password` VARCHAR(45) NULL,
  `SSN` INT NOT NULL,
  `FName` VARCHAR(45) NULL,
  `LName` VARCHAR(45) NULL,
  `Salary` INT NULL,
  `JobTitle` VARCHAR(45) NULL,
  PRIMARY KEY (`UserID`),
  UNIQUE INDEX `UserID_UNIQUE` (`UserID` ASC) VISIBLE,
  UNIQUE INDEX `SSN_UNIQUE` (`SSN` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`NURSE`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`NURSE` ;

CREATE TABLE IF NOT EXISTS `mydb`.`NURSE` (
  `UserID` INT NOT NULL,
  `WARD_WardID` INT NOT NULL,
  PRIMARY KEY (`UserID`, `WARD_WardID`),
  UNIQUE INDEX `UserID_UNIQUE` (`UserID` ASC) VISIBLE,
  CONSTRAINT `UserID`
    FOREIGN KEY (`UserID`)
    REFERENCES `mydb`.`STAFF` (`UserID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `WARD_WardID`
    FOREIGN KEY (`WARD_WardID`)
    REFERENCES `mydb`.`WARD` (`WardID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`DOCTOR`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`DOCTOR` ;

CREATE TABLE IF NOT EXISTS `mydb`.`DOCTOR` (
  `UserID` INT NOT NULL,
  `IsSpecialist` TINYINT NOT NULL,
  `Specialty` VARCHAR(45) NULL,
  PRIMARY KEY (`UserID`),
  UNIQUE INDEX `UserID_UNIQUE` (`UserID` ASC) VISIBLE,
  CONSTRAINT `UserID`
    FOREIGN KEY (`UserID`)
    REFERENCES `mydb`.`STAFF` (`UserID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ADMIN`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`ADMIN` ;

CREATE TABLE IF NOT EXISTS `mydb`.`ADMIN` (
  `UserID` INT NOT NULL,
  `ClearanceLevel` INT NOT NULL,
  PRIMARY KEY (`UserID`),
  UNIQUE INDEX `UserID_UNIQUE` (`UserID` ASC) VISIBLE,
  CONSTRAINT `UserID`
    FOREIGN KEY (`UserID`)
    REFERENCES `mydb`.`STAFF` (`UserID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`DOCTOR_DEGREES`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`DOCTOR_DEGREES` ;

CREATE TABLE IF NOT EXISTS `mydb`.`DOCTOR_DEGREES` (
  `DOCTOR_UserID` INT NOT NULL,
  `Degree` VARCHAR(128) NOT NULL,
  PRIMARY KEY (`DOCTOR_UserID`),
  CONSTRAINT `DOCTOR_UserID`
    FOREIGN KEY (`DOCTOR_UserID`)
    REFERENCES `mydb`.`DOCTOR` (`UserID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`NURSES_CERTIFICATION`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`NURSES_CERTIFICATION` ;

CREATE TABLE IF NOT EXISTS `mydb`.`NURSES_CERTIFICATION` (
  `NURSE_UserID` INT NOT NULL,
  `Certification` VARCHAR(128) NOT NULL,
  PRIMARY KEY (`NURSE_UserID`),
  CONSTRAINT `NURSE_UserID`
    FOREIGN KEY (`NURSE_UserID`)
    REFERENCES `mydb`.`NURSE` (`UserID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`APPOINTMENT`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`APPOINTMENT` ;

CREATE TABLE IF NOT EXISTS `mydb`.`APPOINTMENT` (
  `PATIENT_UserID` INT NOT NULL,
  `Time` TIME NULL,
  `Date` DATE NULL,
  `Reason` VARCHAR(128) NULL,
  `DOCTOR_UserID` INT NOT NULL,
  PRIMARY KEY (`PATIENT_UserID`, `DOCTOR_UserID`),
  CONSTRAINT `PATIENT_UserID`
    FOREIGN KEY (`PATIENT_UserID`)
    REFERENCES `mydb`.`PATIENTS` (`USERID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `DOCTOR_UserID`
    FOREIGN KEY (`DOCTOR_UserID`)
    REFERENCES `mydb`.`DOCTOR` (`UserID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`PRESCRIBED`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`PRESCRIBED` ;

CREATE TABLE IF NOT EXISTS `mydb`.`PRESCRIBED` (
  `PATIENT_UserID` INT NOT NULL,
  `DOCTOR_UserID` INT NOT NULL,
  `MEDICINE_MedicineID` INT NOT NULL,
  `Dosage` VARCHAR(45) NULL,
  `Frequency` VARCHAR(45) NULL,
  `IsRefillable` TINYINT NULL,
  PRIMARY KEY (`PATIENT_UserID`, `DOCTOR_UserID`, `MEDICINE_MedicineID`),
  INDEX `DOCTOR_UserID_idx` (`DOCTOR_UserID` ASC) VISIBLE,
  INDEX `MEDICINE_MedicineID_idx` (`MEDICINE_MedicineID` ASC) VISIBLE,
  CONSTRAINT `PATIENT_UserID`
    FOREIGN KEY (`PATIENT_UserID`)
    REFERENCES `mydb`.`PATIENTS` (`USERID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `DOCTOR_UserID`
    FOREIGN KEY (`DOCTOR_UserID`)
    REFERENCES `mydb`.`DOCTOR` (`UserID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `MEDICINE_MedicineID`
    FOREIGN KEY (`MEDICINE_MedicineID`)
    REFERENCES `mydb`.`MEDICINE` (`MedicineID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`DOCTOR_IS_IN_WARD`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`DOCTOR_IS_IN_WARD` ;

CREATE TABLE IF NOT EXISTS `mydb`.`DOCTOR_IS_IN_WARD` (
  `DOCTOR_UserID` INT NOT NULL,
  `WARD_WardID` INT NOT NULL,
  PRIMARY KEY (`DOCTOR_UserID`, `WARD_WardID`),
  INDEX `WARD_WardID_idx` (`WARD_WardID` ASC) VISIBLE,
  CONSTRAINT `DOCTOR_UserID`
    FOREIGN KEY (`DOCTOR_UserID`)
    REFERENCES `mydb`.`DOCTOR` (`UserID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `WARD_WardID`
    FOREIGN KEY (`WARD_WardID`)
    REFERENCES `mydb`.`WARD` (`WardID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`PATIENT_IS_IN_WARD`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`PATIENT_IS_IN_WARD` ;

CREATE TABLE IF NOT EXISTS `mydb`.`PATIENT_IS_IN_WARD` (
  `PATIENT_UserID` INT NOT NULL,
  `WARD_WardID` INT NOT NULL,
  PRIMARY KEY (`PATIENT_UserID`, `WARD_WardID`),
  INDEX `WARD_WardID_idx` (`WARD_WardID` ASC) VISIBLE,
  CONSTRAINT `PATIENT_UserID`
    FOREIGN KEY (`PATIENT_UserID`)
    REFERENCES `mydb`.`PATIENTS` (`USERID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `WARD_WardID`
    FOREIGN KEY (`WARD_WardID`)
    REFERENCES `mydb`.`WARD` (`WardID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`PATIENT_IS_IN_ROOM`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`PATIENT_IS_IN_ROOM` ;

CREATE TABLE IF NOT EXISTS `mydb`.`PATIENT_IS_IN_ROOM` (
  `PATIENT_UserID` INT NOT NULL,
  `ROOM_Room#` INT NOT NULL,
  PRIMARY KEY (`PATIENT_UserID`, `ROOM_Room#`),
  INDEX `ROOM_Room#_idx` (`ROOM_Room#` ASC) VISIBLE,
  CONSTRAINT `PATIENT_UserID`
    FOREIGN KEY (`PATIENT_UserID`)
    REFERENCES `mydb`.`PATIENTS` (`USERID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `ROOM_Room#`
    FOREIGN KEY (`ROOM_Room#`)
    REFERENCES `mydb`.`ROOMS` (`Room#`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
