-- MySQL Script generated by MySQL Workbench
-- Mon Dec  2 22:48:40 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`staff`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`staff` ;

CREATE TABLE IF NOT EXISTS `mydb`.`staff` (
  `STAFF_UserID_pk` INT(11) NOT NULL,
  `Password` VARCHAR(45) NULL DEFAULT NULL,
  `SSN` INT(11) NOT NULL,
  `FName` VARCHAR(45) NULL DEFAULT NULL,
  `LName` VARCHAR(45) NULL DEFAULT NULL,
  `Salary` INT(11) NULL DEFAULT NULL,
  `JobTitle` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`STAFF_UserID_pk`),
  UNIQUE INDEX `UserID_UNIQUE` (`STAFF_UserID_pk` ASC) VISIBLE,
  UNIQUE INDEX `SSN_UNIQUE` (`SSN` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`admin`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`admin` ;

CREATE TABLE IF NOT EXISTS `mydb`.`admin` (
  `ADMIN_UserID_fk` INT(11) NOT NULL,
  `ClearanceLevel` INT(11) NOT NULL,
  PRIMARY KEY (`ADMIN_UserID_fk`),
  UNIQUE INDEX `UserID_UNIQUE` (`ADMIN_UserID_fk` ASC) VISIBLE,
  CONSTRAINT `ADMIN_UserID_fk`
    FOREIGN KEY (`ADMIN_UserID_fk`)
    REFERENCES `mydb`.`staff` (`STAFF_UserID_pk`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`doctor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`doctor` ;

CREATE TABLE IF NOT EXISTS `mydb`.`doctor` (
  `DOCTOR_UserID_fk` INT(11) NOT NULL,
  `IsSpecialist` TINYINT(4) NOT NULL,
  `Specialty` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`DOCTOR_UserID_fk`),
  UNIQUE INDEX `UserID_UNIQUE` (`DOCTOR_UserID_fk` ASC) VISIBLE,
  CONSTRAINT `DOCTOR_UserID_fk`
    FOREIGN KEY (`DOCTOR_UserID_fk`)
    REFERENCES `mydb`.`staff` (`STAFF_UserID_pk`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`patients`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`patients` ;

CREATE TABLE IF NOT EXISTS `mydb`.`patients` (
  `PATIENTS_USERID_pk` INT(11) NOT NULL,
  `Password` VARCHAR(45) NULL DEFAULT NULL,
  `FName` VARCHAR(45) NULL DEFAULT NULL,
  `LName` VARCHAR(45) NULL DEFAULT NULL,
  `HealthCareNum` INT(11) NOT NULL,
  PRIMARY KEY (`PATIENTS_USERID_pk`),
  UNIQUE INDEX `USERID_UNIQUE` (`PATIENTS_USERID_pk` ASC) VISIBLE,
  UNIQUE INDEX `HealthCare#_UNIQUE` (`HealthCareNum` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`appointment`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`appointment` ;

CREATE TABLE IF NOT EXISTS `mydb`.`appointment` (
  `PATIENT_UserID` INT(11) NOT NULL,
  `Time` TIME NULL DEFAULT NULL,
  `Date` DATE NULL DEFAULT NULL,
  `Reason` VARCHAR(128) NULL DEFAULT NULL,
  `DAPT_UserID_fk` INT(11) NOT NULL,
  INDEX `DAPT_UserID_fk` (`DAPT_UserID_fk` ASC) VISIBLE,
  CONSTRAINT `DAPT_UserID_fk`
    FOREIGN KEY (`DAPT_UserID_fk`)
    REFERENCES `mydb`.`doctor` (`DOCTOR_UserID_fk`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `PAPT_UserID_fk`
    FOREIGN KEY (`PATIENT_UserID`)
    REFERENCES `mydb`.`patients` (`PATIENTS_USERID_pk`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`ward`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`ward` ;

CREATE TABLE IF NOT EXISTS `mydb`.`ward` (
  `WardID_pk` INT(11) NOT NULL,
  `Name` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`WardID_pk`),
  UNIQUE INDEX `WARD_ID_UNIQUE` (`WardID_pk` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`bed`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`bed` ;

CREATE TABLE IF NOT EXISTS `mydb`.`bed` (
  `BedNum_pk` INT(11) NOT NULL,
  `BED_WardID_fk` INT(11) NOT NULL,
  PRIMARY KEY (`BedNum_pk`, `BED_WardID_fk`),
  UNIQUE INDEX `Bed#_UNIQUE` (`BedNum_pk` ASC) VISIBLE,
  INDEX `BED_WardID_fk` (`BED_WardID_fk` ASC) VISIBLE,
  CONSTRAINT `BED_WardID_fk`
    FOREIGN KEY (`BED_WardID_fk`)
    REFERENCES `mydb`.`ward` (`WardID_pk`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`doctor_degrees`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`doctor_degrees` ;

CREATE TABLE IF NOT EXISTS `mydb`.`doctor_degrees` (
  `DOCDEG_UserID_fk` INT(11) NOT NULL,
  `Degree` VARCHAR(128) NOT NULL,
  CONSTRAINT `DOCDEG_UserID_fk`
    FOREIGN KEY (`DOCDEG_UserID_fk`)
    REFERENCES `mydb`.`doctor` (`DOCTOR_UserID_fk`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`doctor_is_in_ward`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`doctor_is_in_ward` ;

CREATE TABLE IF NOT EXISTS `mydb`.`doctor_is_in_ward` (
  `DW_UserID_fk` INT(11) NOT NULL,
  `DW_WardID_fk` INT(11) NOT NULL,
  INDEX `WARD_WardID_idx` (`DW_WardID_fk` ASC) VISIBLE,
  CONSTRAINT `DW_UserID_fk`
    FOREIGN KEY (`DW_UserID_fk`)
    REFERENCES `mydb`.`doctor` (`DOCTOR_UserID_fk`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `DW_WardID_fk`
    FOREIGN KEY (`DW_WardID_fk`)
    REFERENCES `mydb`.`ward` (`WardID_pk`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`rooms`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`rooms` ;

CREATE TABLE IF NOT EXISTS `mydb`.`rooms` (
  `RoomNum_pk` INT(11) NOT NULL,
  `Name` VARCHAR(45) NULL DEFAULT NULL,
  `ROOMS_WardID_fk` INT(11) NOT NULL,
  PRIMARY KEY (`RoomNum_pk`, `ROOMS_WardID_fk`),
  UNIQUE INDEX `Room#_UNIQUE` (`RoomNum_pk` ASC) VISIBLE,
  INDEX `ROOM_WardID_fk` (`ROOMS_WardID_fk` ASC) VISIBLE,
  CONSTRAINT `ROOM_WardID_fk`
    FOREIGN KEY (`ROOMS_WardID_fk`)
    REFERENCES `mydb`.`ward` (`WardID_pk`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`equipment`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`equipment` ;

CREATE TABLE IF NOT EXISTS `mydb`.`equipment` (
  `Equiptment_ID_pk` INT(11) NOT NULL,
  `Name` VARCHAR(45) NULL DEFAULT NULL,
  `Type` VARCHAR(45) NULL DEFAULT NULL,
  `EQUIPMENT_RoomNum_fk` INT(11) NOT NULL,
  PRIMARY KEY (`Equiptment_ID_pk`, `EQUIPMENT_RoomNum_fk`),
  UNIQUE INDEX `Equiptment_ID_UNIQUE` (`Equiptment_ID_pk` ASC) VISIBLE,
  INDEX `ROOM_Room#_idx` (`EQUIPMENT_RoomNum_fk` ASC) VISIBLE,
  CONSTRAINT `EQUIPMENT_RoomNum_fk`
    FOREIGN KEY (`EQUIPMENT_RoomNum_fk`)
    REFERENCES `mydb`.`rooms` (`RoomNum_pk`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`medicine`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`medicine` ;

CREATE TABLE IF NOT EXISTS `mydb`.`medicine` (
  `MedicineID_pk` INT(11) NOT NULL,
  `MedicineName` VARCHAR(45) NULL DEFAULT NULL,
  `Form` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`MedicineID_pk`),
  UNIQUE INDEX `MedicineID_UNIQUE` (`MedicineID_pk` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`nurse`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`nurse` ;

CREATE TABLE IF NOT EXISTS `mydb`.`nurse` (
  `NURSE_UserID_fk` INT(11) NOT NULL,
  `NURSE_WardID_fk` INT(11) NOT NULL,
  UNIQUE INDEX `UserID_UNIQUE` (`NURSE_UserID_fk` ASC) VISIBLE,
  INDEX `NURSE_WardID_fk` (`NURSE_WardID_fk` ASC) VISIBLE,
  PRIMARY KEY (`NURSE_UserID_fk`, `NURSE_WardID_fk`),
  CONSTRAINT `NURSE_UserID_fk`
    FOREIGN KEY (`NURSE_UserID_fk`)
    REFERENCES `mydb`.`staff` (`STAFF_UserID_pk`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `NURSE_WardID_fk`
    FOREIGN KEY (`NURSE_WardID_fk`)
    REFERENCES `mydb`.`ward` (`WardID_pk`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`nurses_certification`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`nurses_certification` ;

CREATE TABLE IF NOT EXISTS `mydb`.`nurses_certification` (
  `NURCER_UserID_fk` INT(11) NOT NULL,
  `Certification` VARCHAR(128) NOT NULL,
  CONSTRAINT `NURCER_UserID_fk`
    FOREIGN KEY (`NURCER_UserID_fk`)
    REFERENCES `mydb`.`nurse` (`NURSE_UserID_fk`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`patient_is_in_room`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`patient_is_in_room` ;

CREATE TABLE IF NOT EXISTS `mydb`.`patient_is_in_room` (
  `PR_UserID_fk` INT(11) NOT NULL,
  `PR_RoomNum_fk` INT(11) NOT NULL,
  INDEX `ROOM_Room#_idx` (`PR_RoomNum_fk` ASC) VISIBLE,
  UNIQUE INDEX `PR_UserID_fk_UNIQUE` (`PR_UserID_fk` ASC) VISIBLE,
  CONSTRAINT `PR_RoomNum_fk`
    FOREIGN KEY (`PR_RoomNum_fk`)
    REFERENCES `mydb`.`rooms` (`RoomNum_pk`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `PR_UserID_fk`
    FOREIGN KEY (`PR_UserID_fk`)
    REFERENCES `mydb`.`patients` (`PATIENTS_USERID_pk`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`patient_is_in_ward`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`patient_is_in_ward` ;

CREATE TABLE IF NOT EXISTS `mydb`.`patient_is_in_ward` (
  `PW_UserID_fk` INT(11) NOT NULL,
  `PW_WardID_fk` INT(11) NOT NULL,
  INDEX `WARD_WardID_idx` (`PW_WardID_fk` ASC) VISIBLE,
  UNIQUE INDEX `PW_UserID_fk_UNIQUE` (`PW_UserID_fk` ASC) VISIBLE,
  CONSTRAINT `PW_UserID_fk`
    FOREIGN KEY (`PW_UserID_fk`)
    REFERENCES `mydb`.`patients` (`PATIENTS_USERID_pk`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `PW_WardID_fk`
    FOREIGN KEY (`PW_WardID_fk`)
    REFERENCES `mydb`.`ward` (`WardID_pk`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`prescribed`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`prescribed` ;

CREATE TABLE IF NOT EXISTS `mydb`.`prescribed` (
  `PPRESC_UserID_fk` INT(11) NOT NULL,
  `DPRESC_UserID_fk` INT(11) NOT NULL,
  `MEDICINE_MedicineID` INT(11) NOT NULL,
  `Dosage` VARCHAR(45) NULL DEFAULT NULL,
  `Frequency` VARCHAR(45) NULL DEFAULT NULL,
  `IsRefillable` TINYINT(4) NULL DEFAULT NULL,
  INDEX `DOCTOR_UserID_idx` (`DPRESC_UserID_fk` ASC) VISIBLE,
  INDEX `MEDICINE_MedicineID_idx` (`MEDICINE_MedicineID` ASC) VISIBLE,
  CONSTRAINT `DPRESC_UserID_fk`
    FOREIGN KEY (`DPRESC_UserID_fk`)
    REFERENCES `mydb`.`doctor` (`DOCTOR_UserID_fk`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `MPRESC_MedicineID_fk`
    FOREIGN KEY (`MEDICINE_MedicineID`)
    REFERENCES `mydb`.`medicine` (`MedicineID_pk`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `PPRESC_UserID_fk`
    FOREIGN KEY (`PPRESC_UserID_fk`)
    REFERENCES `mydb`.`patients` (`PATIENTS_USERID_pk`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
